"""
Rule-Based Report Generator — Pure formatting of DecisionResult (Type 3 thesis).

No interpretation; only renders DecisionResult. Recommendations come from
decision_result.recommendations only (generated by decision engine).
Numeric format: :,.2f for sales-like values; no currency symbols.
"""

from decision_engine import DecisionResult, RULE_DEFINITIONS


def get_rule_definitions():
    """Returns RULE_DEFINITIONS for UI and documentation."""
    return RULE_DEFINITIONS.copy()


def _fmt_sales(value: float) -> str:
    """Format sales-like values consistently; no currency symbols."""
    return f"{value:,.2f}"


def generate_rule_based_report(decision_result: DecisionResult) -> str:
    """
    Generate report from rule-based decision outcomes.
    All content derived from DecisionResult; recommendations from decision_result.recommendations only.
    """
    kpis = decision_result.kpis
    sections = []

    sections.append("## 1. Overview")
    sections.append(
        f"Total sales across the period amount to {_fmt_sales(kpis.total_sales)}. "
        f"The dataset covers orders from {kpis.date_range[0]} to {kpis.date_range[1]}."
    )
    sections.append("")

    sections.append("## 2. Trends")
    if decision_result.trend:
        t = decision_result.trend
        direction = "increased" if t.mom_change_pct >= 0 else "decreased"
        sections.append(
            f"Monthly sales {direction} from {t.prev_month} ({_fmt_sales(t.prev_sales)}) to "
            f"{t.latest_month} ({_fmt_sales(t.latest_sales)}). Change: {t.mom_change_pct:+.1f}%."
        )
        sections.append(f"Decision: {t.label.upper()} — {t.rule_explanation}")
    else:
        sections.append("Insufficient months for trend analysis.")
    sections.append("")

    sections.append("## 3. Top Drivers")
    if kpis.top_categories:
        top_cat = kpis.top_categories[0]
        sections.append(f"Top category by sales: {top_cat['category']} ({_fmt_sales(top_cat['sales'])}).")
    if kpis.top_products:
        top_prod = kpis.top_products[0]
        sections.append(f"Top product: {top_prod['product']} ({_fmt_sales(top_prod['sales'])}).")
    if kpis.top_categories or kpis.top_products:
        sections.append("Full top-5 lists are available in the KPI tables.")
    else:
        sections.append("No category or product data available.")
    sections.append("")

    sections.append("## 4. Regional Insights")
    if kpis.regional_distribution:
        top_region = kpis.regional_distribution[0]
        sections.append(
            f"Strongest region: {top_region['region']} with {_fmt_sales(top_region['sales'])} "
            f"({top_region['share_pct']:.1f}% of total sales)."
        )
        for c in decision_result.concentration:
            if c.entity_type == "region" and c.entity_name == top_region["region"]:
                sections.append(f"Concentration decision: {c.label.upper()} — {c.rule_explanation}")
                break
        for r in kpis.regional_distribution[1:]:
            sections.append(f"- {r['region']}: {_fmt_sales(r['sales'])} ({r['share_pct']:.1f}%)")
    else:
        sections.append("No regional data available.")
    sections.append("")

    sections.append("## 5. Anomalies")
    if decision_result.anomalies:
        for a in decision_result.anomalies:
            sections.append(
                f"- {a.month}: {a.type.upper()} — sales {_fmt_sales(a.sales)} (z-score: {a.z_score:.2f})"
            )
            sections.append(f"  Decision: {a.label.upper()} — {a.rule_explanation}")
    else:
        sections.append("No significant anomalies detected in monthly sales.")
    sections.append("")

    sections.append("## 6. Concentration")
    if decision_result.concentration:
        for c in decision_result.concentration:
            sections.append(f"- {c.entity_type.title()} '{c.entity_name}': {c.share_pct:.1f}% — {c.label.upper()}")
            sections.append(f"  {c.rule_explanation}")
    else:
        sections.append("No concentration analysis available.")
    sections.append("")

    sections.append("## 7. Recommendations")
    if decision_result.recommendations:
        for i, r in enumerate(decision_result.recommendations, 1):
            sections.append(f"{i}. {r}")
    else:
        sections.append("No rule-triggered recommendations for this run.")

    return "\n".join(sections)
